#pragma once
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <exception>
#include <string>
#include <map>
#include <list>
#include <vector>
#include <deque>
#include <stack>
#include <queue>
#include <fstream>
#include <utility>
#include <exception>
#include "boost/regex.hpp"
#include "boost/asio.hpp"
#include "boost/thread.hpp"
#include "boost/bind.hpp"
#include "boost/algorithm/string.hpp"