#pragma once
#include <cstdlib>
#include <iostream>
#include <string>
#include <map>
#include <list>
#include <vector>
#include <deque>
#include <stack>
#include <queue>
#include <fstream>
#include <utility>
#include <exception>
#include "boost\regex.hpp"